- name: Create an instance
  hosts: localhost
  gather_facts: no
  vars:
      zone: "asia-southeast1-c"
      region: "asia-southeast1"
  tasks:
   - name: create a disk
     gcp_compute_disk:
         name: "{{ vmname }}"
         size_gb: "{{ size }}"
         source_image: 'projects/{{ linux }}-cloud/global/images/family/{{ linux }}-{{ versi }}'
         zone: "{{ zone }}"
         scopes:
           - https://www.googleapis.com/auth/compute
         state: present
     register: disk
   - name: create a address
     gcp_compute_address:
         name: "{{ vmname }}"
         region: "{{ region }}"
         scopes:
           - https://www.googleapis.com/auth/compute
         state: present
     register: address
   - name: create a instance
     gcp_compute_instance:
         state: present
         name: "{{ vmname }}"
         machine_type: "{{ machine }}"
         disks:
           - auto_delete: true
             boot: true
             source: "{{ disk }}"
         network_interfaces:
             - network:
               access_configs:
                 - name: 'External NAT'
                   nat_ip: 
                   type: 'ONE_TO_ONE_NAT'
         zone: "{{ zone }}"
         scopes:
           - https://www.googleapis.com/auth/compute
     register: instance
