- name: Create an instance
  hosts: localhost
  gather_facts: no
  vars_prompt:
    - name: vmname
      prompt: "Enter VM name"
      default: "test"
      private: no
    - name: size
      prompt: "Enter VM disk size (in gigabyte)"
      default: "10"
      private: no
    - name: versi
      prompt: "Enter Ubuntu VM version (1604, 1804)"
      default: "1804"
      private: no
    - name: machine
      prompt: "Enter VM machine type (f1-micro or g1-small or n1-standard-1"
      default: "f1-micro"
      private: no
  vars:
      gcp_project: widansible
      gcp_cred_kind: serviceaccount
      gcp_cred_file: /data/gcp/widansible-e50257d17b67.json
      zone: "asia-southeast1-c"
      region: "asia-southeast1"
  tasks:
   - name: create a disk
     gcp_compute_disk:
         name: "{{ vmname }}"
         size_gb: "{{ size }}"
         source_image: 'projects/ubuntu-os-cloud/global/images/family/ubuntu-minimal-{{ versi }}-lts'
         zone: "{{ zone }}"
         project: "{{ gcp_project }}"
         auth_kind: "{{ gcp_cred_kind }}"
         service_account_file: "{{ gcp_cred_file }}"
         scopes:
           - https://www.googleapis.com/auth/compute
         state: present
     register: disk
   - name: create a instance
     gcp_compute_instance:
         state: present
         name: "{{ vmname }}"
         machine_type: "{{ machine }}"
         disks:
           - auto_delete: true
             boot: true
             source: "{{ disk }}"
         network_interfaces:
             - network:
               access_configs:
                 - name: 'External NAT'
                   nat_ip: 
                   type: 'ONE_TO_ONE_NAT'
         zone: "{{ zone }}"
         project: "{{ gcp_project }}"
         auth_kind: "{{ gcp_cred_kind }}"
         service_account_file: "{{ gcp_cred_file }}"
         scopes:
           - https://www.googleapis.com/auth/compute
     register: instance
