- name: Create an instance
  hosts: localhost
  gather_facts: no
  vars:
      zone: "asia-southeast1-c"
      region: "asia-southeast1"
  tasks:
   - name: create a disk
     gcp_compute_disk:
         name: "{{ vmname }}"
         size_gb: "{{ size }}"
         source_image: 'projects/{{ linux }}-cloud/global/images/family/{{ linux }}-{{ versi }}'
         zone: "{{ zone }}"
         scopes:
           - https://www.googleapis.com/auth/compute
         state: present
     register: disk
   - name: create a address
     gcp_compute_address:
         name: "{{ vmname }}"
         region: "{{ region }}"
         scopes:
           - https://www.googleapis.com/auth/compute
         state: present
     register: address
   - name: create a instance
     gcp_compute_instance:
         state: present
         name: "{{ vmname }}"
         machine_type: "{{ machine }}"
         disks:
           - auto_delete: true
             boot: true
             source: "{{ disk }}"
         network_interfaces:
             - network:
               access_configs:
                 - name: 'External NAT'
                   nat_ip: 
                   type: 'ONE_TO_ONE_NAT'
         zone: "{{ zone }}"
         scopes:
           - https://www.googleapis.com/auth/compute
     register: instance
   - debug:
       var: address.address
   - name: Wait for SSH to come up
     wait_for: host={{ address.address }} port=22 delay=10 timeout=60
   - name: Add host to groupname
     add_host: hostname={{ address.address }} groupname=new_instances

- name: Manage new instances
  hosts: new_instances
  connection: ssh
  sudo: True
  tasks:
   - name: install openscap scanner
     package:
       name: ['openscap-scanner, scap-security-guide']
       state: latest

   - name: Create backup directory
       file:
       path: /data/backups/etc/ssh
       owner: root
       group: root
       state: directory
   - name: Backup sshd_config
     fetch:
       src: /etc/ssh/sshd_config
       dest: ./backups/sshd_config
       flat: yes
   - name: Copy sshd_config
     copy:
       src: ./backups/sshd_config
       dest: /data/backups/etc/ssh/sshd_config
       owner: root
       group: root
       mode: '0600'
   - name: Deduplicate values from /etc/ssh/sshd_config
     lineinfile:
       backup: yes
       path: /etc/ssh/sshd_config
       create: false
       regexp: (?i)^\s*Port
       state: absent
   - name: Insert correct line to /etc/ssh/sshd_config
     lineinfile:
       path: /etc/ssh/sshd_config
       create: true
       line: Port 3943
       state: present
       insertafter: ^#?Port
       validate: /usr/sbin/sshd -t -f %s
   - name: Insert correct line to /etc/ssh/sshd_config
     lineinfile:
       path: /etc/ssh/sshd_config
       create: true
       line: Port 22
       state: present
       insertafter: ^#?Port
       validate: /usr/sbin/sshd -t -f %s
   - name: Restart service sshd, in all cases
     service:
       name: sshd
       state: restarted
   - name: Allow sshd to listen on tcp port 3943
     seport:
       ports: 3943
       proto: tcp
       setype: ssh_port_t
       state: present
   - name: Restart service sshd, in all cases
     service:
       name: sshd
       state: restarted
